sudo: required
addons:
  chrome: stable
  ssh_known_hosts: 140.143.235.188
language: node_js
os: osx
node_js:
- 10.11.0
branchs:
  only:
  - master
install: npm install
script: npm run test
notifications:
  email:
    recipients:
    - 719197352@qq.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_9b1c931e4063_key -iv $encrypted_9b1c931e4063_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh ubuntu@140.143.235.188 < ./build.sh