export enum Color {
    'amber' = 'amber',
    'blue' = 'blue',
    'blueGrey' = 'blueGrey',
    'brown' = 'brown',
    'common' = 'common',
    'cyan' = 'cyan',
    'deepOrange' = 'deepOrange',
    'deepPurple' = 'deepPurple',
    'green' = 'green',
    'grey' = 'grey',
    'indigo' = 'indigo',
    'lightBlue' = 'lightBlue',
    'lightGreen' = 'lightGreen',
    'lime' = 'lime',
    'orange' = 'orange',
    'pink' = 'pink',
    'purple' = 'purple',
    'red' = 'red',
    'teal' = 'teal',
    'yellow' = 'yellow',
}
